version: '3.8'

services:
  frontend:
    image: ${DOCKER_REGISTRY:-localhost}/sqlchat-frontend:${TAG:-latest}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_R_SERVER_URL=${R_SERVER_URL:-http://localhost:3001}
      - NEXT_PUBLIC_N8N_URL=${N8N_URL:-http://localhost:5678}
    depends_on:
      - r-server
      - n8n
    restart: unless-stopped
    networks:
      - sqlchat-network

  r-server:
    image: ${DOCKER_REGISTRY:-localhost}/sqlchat-r-server:${TAG:-latest}
    ports:
      - "${R_SERVER_PORT:-3001}:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - SERVER_URL=${R_SERVER_URL:-http://localhost:3001}
    volumes:
      - r-server-data:/app/public
      - r-server-logs:/app/logs
    restart: unless-stopped
    networks:
      - sqlchat-network
      
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your-encryption-key-here}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678/}
      - EXECUTIONS_PROCESS=main
      - GENERIC_TIMEZONE=${TIMEZONE:-Europe/Moscow}
      # Подключение к PostgreSQL
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB_N8N:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER_N8N:-n8n}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD_N8N:-n8n}
      # OpenAI API
      - N8N_OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key}
    volumes:
      - n8n-data:/home/node/.n8n
      - ./workflows:/home/node/workflows
      - ./credentials:/home/node/.n8n/credentials
    restart: unless-stopped
    networks:
      - sqlchat-network
    depends_on:
      - postgres
      
  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-sqlchat}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/backup:/backup
    restart: unless-stopped
    networks:
      - sqlchat-network

networks:
  sqlchat-network:
    driver: bridge

volumes:
  r-server-data:
  r-server-logs:
  n8n-data:
  postgres-data: 